// <auto-generated />
using API_Padaria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace trabalho.Migrations
{
    [DbContext(typeof(PadariaDbContext))]
    [Migration("20230919053417_ClasseDoceAdicionada")]
    partial class ClasseDoceAdicionada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("API_Padaria.Models.Doce", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preço")
                        .HasColumnType("TEXT");

                    b.HasKey("Nome");

                    b.ToTable("Doce");
                });

            modelBuilder.Entity("API_Padaria.Models.Salgado", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preço")
                        .HasColumnType("TEXT");

                    b.HasKey("Nome");

                    b.ToTable("Salgado");
                });
#pragma warning restore 612, 618
        }
    }
}
