// <auto-generated />
using System;
using API_Padaria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace trabalho.Migrations
{
    [DbContext(typeof(PadariaDbContext))]
    [Migration("20230924193657_MudançaModelsControllers")]
    partial class MudançaModelsControllers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("API_Padaria.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("API_Padaria.Models.Doce", b =>
                {
                    b.Property<string>("NomeDoce")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreçoDoce")
                        .HasColumnType("TEXT");

                    b.HasKey("NomeDoce");

                    b.ToTable("Doce");
                });

            modelBuilder.Entity("API_Padaria.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("API_Padaria.Models.Salgado", b =>
                {
                    b.Property<string>("NomeSalgado")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreçoSalgado")
                        .HasColumnType("TEXT");

                    b.HasKey("NomeSalgado");

                    b.ToTable("Salgado");
                });
#pragma warning restore 612, 618
        }
    }
}
