// <auto-generated />
using API_Padaria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace trabalho.Migrations
{
    [DbContext(typeof(PadariaDbContext))]
    [Migration("20230919051756_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("API_Padaria.Models.Salgado", b =>
                {
                    b.Property<string>("Preço")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.HasKey("Preço");

                    b.ToTable("Salgado");
                });
#pragma warning restore 612, 618
        }
    }
}
